[package]
name = "rk-storage"
version.workspace = true
edition.workspace = true

[dependencies]
rk-core = { workspace = true }
rk-protocol = { workspace = true }
bytes = { workspace = true }
memmap2 = { workspace = true }
crc32c = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
serde_json = { workspace = true }
