[package]
name = "rk-controller"
version.workspace = true
edition.workspace = true

[dependencies]
rk-core = { workspace = true }
openraft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
dashmap = { workspace = true }
