{{- if and .Values.security.sasl.enabled .Values.security.sasl.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "r-kafka.fullname" . }}-sasl
  labels:
    {{- include "r-kafka.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range .Values.security.sasl.users }}
  {{ .username }}: {{ .password | b64enc | quote }}
  {{- end }}
{{- end }}
