//! Kafka 标准错误码
//!
//! 值与 Apache Kafka 完全一致。
//! 参考: <https://kafka.apache.org/protocol.html#protocol_error_codes>

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(i16)]
pub enum KafkaErrorCode {
    UnknownServerError = -1,
    None = 0,
    OffsetOutOfRange = 1,
    CorruptMessage = 2,
    UnknownTopicOrPartition = 3,
    InvalidFetchSize = 4,
    LeaderNotAvailable = 5,
    NotLeaderOrFollower = 6,
    RequestTimedOut = 7,
    BrokerNotAvailable = 8,
    ReplicaNotAvailable = 9,
    MessageTooLarge = 10,
    StaleControllerEpoch = 11,
    OffsetMetadataTooLarge = 12,
    NetworkException = 13,
    CoordinatorLoadInProgress = 14,
    CoordinatorNotAvailable = 15,
    NotCoordinator = 16,
    InvalidTopicException = 17,
    RecordListTooLarge = 18,
    NotEnoughReplicas = 19,
    NotEnoughReplicasAfterAppend = 20,
    InvalidRequiredAcks = 21,
    IllegalGeneration = 22,
    InconsistentGroupProtocol = 23,
    InvalidGroupId = 24,
    UnknownMemberId = 25,
    InvalidSessionTimeout = 26,
    RebalanceInProgress = 27,
    InvalidCommitOffsetSize = 28,
    TopicAuthorizationFailed = 29,
    GroupAuthorizationFailed = 30,
    ClusterAuthorizationFailed = 31,
    InvalidTimestamp = 32,
    UnsupportedSaslMechanism = 33,
    IllegalSaslState = 34,
    UnsupportedVersion = 35,
    TopicAlreadyExists = 36,
    InvalidPartitions = 37,
    InvalidReplicationFactor = 38,
    InvalidReplicaAssignment = 39,
    InvalidConfig = 40,
    NotController = 41,
    InvalidRequest = 42,
    UnsupportedForMessageFormat = 43,
    PolicyViolation = 44,
    OutOfOrderSequenceNumber = 45,
    DuplicateSequenceNumber = 46,
    InvalidProducerEpoch = 47,
    InvalidTxnState = 48,
    InvalidProducerIdMapping = 49,
    InvalidTransactionTimeout = 50,
    ConcurrentTransactions = 51,
    TransactionCoordinatorFenced = 52,
    InvalidProducerId = 53,
    InvalidSequenceNumber = 54,
    InvalidEpoch = 55,
    FencedLeaderEpoch = 56,
    UnknownLeaderEpoch = 57,
    UnsupportedCompressionType = 58,
    StaleBrokerEpoch = 59,
    OffsetNotAvailable = 60,
    MemberIdRequired = 61,
    PreferredLeaderNotAvailable = 62,
    GroupMaxSizeReached = 63,
    FencedInstanceId = 64,
    EligibleLeadersNotAvailable = 65,
    NoReassignmentInProgress = 66,
    GroupSubscribedToTopic = 67,
    InvalidRecord = 68,
    UnstableOffsetCommit = 69,
    ThrottlingQuotaExceeded = 70,
    ProducerFenced = 71,
    ResourceNotFound = 72,
    DuplicateResource = 73,
    UnacceptableCredential = 74,
    InconsistentVoterSet = 75,
    InvalidVotingKey = 76,
    InvalidMetadataVersion = 77,
    TopicDeletionDisabled = 78,
    FencedLeaderEpoch2 = 79, // alias: LeaderNotAvailable in newer versions
    KafkaStorageError = 80,
    LogDirNotFound = 81,
    SaslAuthenticationFailed = 82,
    UnknownProducerId = 83,
    ReassignmentInProgress = 84,
    DelegationTokenAuthDisabled = 85,
    DelegationTokenNotFound = 86,
    DelegationTokenOwnerMismatch = 87,
    DelegationTokenRequestNotAllowed = 88,
    DelegationTokenAuthorizationFailed = 89,
    DelegationTokenExpired = 90,
    InvalidPrincipalType = 91,
    NonEmptyGroup = 92,
    GroupIdNotFound = 93,
    FetchSessionIdNotFound = 94,
    InvalidFetchSessionEpoch = 95,
    ListenerNotFound = 96,
    TopicExistsException = 97,
    InvalidMetadata = 98,
    InvalidUpdateVersion = 99,
    FeatureUpdateFailed = 100,
}

impl KafkaErrorCode {
    pub fn from_i16(v: i16) -> Option<Self> {
        // 使用 match 覆盖全部值
        match v {
            -1 => Some(Self::UnknownServerError),
            0 => Some(Self::None),
            1 => Some(Self::OffsetOutOfRange),
            2 => Some(Self::CorruptMessage),
            3 => Some(Self::UnknownTopicOrPartition),
            4 => Some(Self::InvalidFetchSize),
            5 => Some(Self::LeaderNotAvailable),
            6 => Some(Self::NotLeaderOrFollower),
            7 => Some(Self::RequestTimedOut),
            8 => Some(Self::BrokerNotAvailable),
            9 => Some(Self::ReplicaNotAvailable),
            10 => Some(Self::MessageTooLarge),
            11 => Some(Self::StaleControllerEpoch),
            12 => Some(Self::OffsetMetadataTooLarge),
            13 => Some(Self::NetworkException),
            14 => Some(Self::CoordinatorLoadInProgress),
            15 => Some(Self::CoordinatorNotAvailable),
            16 => Some(Self::NotCoordinator),
            17 => Some(Self::InvalidTopicException),
            18 => Some(Self::RecordListTooLarge),
            19 => Some(Self::NotEnoughReplicas),
            20 => Some(Self::NotEnoughReplicasAfterAppend),
            21 => Some(Self::InvalidRequiredAcks),
            22 => Some(Self::IllegalGeneration),
            23 => Some(Self::InconsistentGroupProtocol),
            24 => Some(Self::InvalidGroupId),
            25 => Some(Self::UnknownMemberId),
            26 => Some(Self::InvalidSessionTimeout),
            27 => Some(Self::RebalanceInProgress),
            28 => Some(Self::InvalidCommitOffsetSize),
            29 => Some(Self::TopicAuthorizationFailed),
            30 => Some(Self::GroupAuthorizationFailed),
            31 => Some(Self::ClusterAuthorizationFailed),
            32 => Some(Self::InvalidTimestamp),
            33 => Some(Self::UnsupportedSaslMechanism),
            34 => Some(Self::IllegalSaslState),
            35 => Some(Self::UnsupportedVersion),
            36 => Some(Self::TopicAlreadyExists),
            37 => Some(Self::InvalidPartitions),
            38 => Some(Self::InvalidReplicationFactor),
            39 => Some(Self::InvalidReplicaAssignment),
            40 => Some(Self::InvalidConfig),
            41 => Some(Self::NotController),
            42 => Some(Self::InvalidRequest),
            43 => Some(Self::UnsupportedForMessageFormat),
            44 => Some(Self::PolicyViolation),
            45 => Some(Self::OutOfOrderSequenceNumber),
            46 => Some(Self::DuplicateSequenceNumber),
            47 => Some(Self::InvalidProducerEpoch),
            48 => Some(Self::InvalidTxnState),
            49 => Some(Self::InvalidProducerIdMapping),
            50 => Some(Self::InvalidTransactionTimeout),
            51 => Some(Self::ConcurrentTransactions),
            52 => Some(Self::TransactionCoordinatorFenced),
            53 => Some(Self::InvalidProducerId),
            54 => Some(Self::InvalidSequenceNumber),
            55 => Some(Self::InvalidEpoch),
            56 => Some(Self::FencedLeaderEpoch),
            57 => Some(Self::UnknownLeaderEpoch),
            58 => Some(Self::UnsupportedCompressionType),
            59 => Some(Self::StaleBrokerEpoch),
            60 => Some(Self::OffsetNotAvailable),
            61 => Some(Self::MemberIdRequired),
            62 => Some(Self::PreferredLeaderNotAvailable),
            63 => Some(Self::GroupMaxSizeReached),
            64 => Some(Self::FencedInstanceId),
            65 => Some(Self::EligibleLeadersNotAvailable),
            66 => Some(Self::NoReassignmentInProgress),
            67 => Some(Self::GroupSubscribedToTopic),
            68 => Some(Self::InvalidRecord),
            69 => Some(Self::UnstableOffsetCommit),
            70 => Some(Self::ThrottlingQuotaExceeded),
            71 => Some(Self::ProducerFenced),
            72 => Some(Self::ResourceNotFound),
            73 => Some(Self::DuplicateResource),
            74 => Some(Self::UnacceptableCredential),
            75 => Some(Self::InconsistentVoterSet),
            76 => Some(Self::InvalidVotingKey),
            77 => Some(Self::InvalidMetadataVersion),
            78 => Some(Self::TopicDeletionDisabled),
            79 => Some(Self::FencedLeaderEpoch2),
            80 => Some(Self::KafkaStorageError),
            81 => Some(Self::LogDirNotFound),
            82 => Some(Self::SaslAuthenticationFailed),
            83 => Some(Self::UnknownProducerId),
            84 => Some(Self::ReassignmentInProgress),
            85 => Some(Self::DelegationTokenAuthDisabled),
            86 => Some(Self::DelegationTokenNotFound),
            87 => Some(Self::DelegationTokenOwnerMismatch),
            88 => Some(Self::DelegationTokenRequestNotAllowed),
            89 => Some(Self::DelegationTokenAuthorizationFailed),
            90 => Some(Self::DelegationTokenExpired),
            91 => Some(Self::InvalidPrincipalType),
            92 => Some(Self::NonEmptyGroup),
            93 => Some(Self::GroupIdNotFound),
            94 => Some(Self::FetchSessionIdNotFound),
            95 => Some(Self::InvalidFetchSessionEpoch),
            96 => Some(Self::ListenerNotFound),
            97 => Some(Self::TopicExistsException),
            98 => Some(Self::InvalidMetadata),
            99 => Some(Self::InvalidUpdateVersion),
            100 => Some(Self::FeatureUpdateFailed),
            _ => None,
        }
    }

    pub fn as_i16(self) -> i16 {
        self as i16
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_error_codes_roundtrip() {
        let all_codes = [
            KafkaErrorCode::UnknownServerError,
            KafkaErrorCode::None,
            KafkaErrorCode::OffsetOutOfRange,
            KafkaErrorCode::CorruptMessage,
            KafkaErrorCode::UnknownTopicOrPartition,
            KafkaErrorCode::InvalidFetchSize,
            KafkaErrorCode::LeaderNotAvailable,
            KafkaErrorCode::NotLeaderOrFollower,
            KafkaErrorCode::RequestTimedOut,
            KafkaErrorCode::BrokerNotAvailable,
            KafkaErrorCode::ReplicaNotAvailable,
            KafkaErrorCode::MessageTooLarge,
            KafkaErrorCode::StaleControllerEpoch,
            KafkaErrorCode::OffsetMetadataTooLarge,
            KafkaErrorCode::NetworkException,
            KafkaErrorCode::CoordinatorLoadInProgress,
            KafkaErrorCode::CoordinatorNotAvailable,
            KafkaErrorCode::NotCoordinator,
            KafkaErrorCode::InvalidTopicException,
            KafkaErrorCode::RecordListTooLarge,
            KafkaErrorCode::NotEnoughReplicas,
            KafkaErrorCode::NotEnoughReplicasAfterAppend,
            KafkaErrorCode::InvalidRequiredAcks,
            KafkaErrorCode::IllegalGeneration,
            KafkaErrorCode::InconsistentGroupProtocol,
            KafkaErrorCode::InvalidGroupId,
            KafkaErrorCode::UnknownMemberId,
            KafkaErrorCode::InvalidSessionTimeout,
            KafkaErrorCode::RebalanceInProgress,
            KafkaErrorCode::InvalidCommitOffsetSize,
            KafkaErrorCode::TopicAuthorizationFailed,
            KafkaErrorCode::GroupAuthorizationFailed,
            KafkaErrorCode::ClusterAuthorizationFailed,
            KafkaErrorCode::InvalidTimestamp,
            KafkaErrorCode::UnsupportedSaslMechanism,
            KafkaErrorCode::IllegalSaslState,
            KafkaErrorCode::UnsupportedVersion,
            KafkaErrorCode::TopicAlreadyExists,
            KafkaErrorCode::InvalidPartitions,
            KafkaErrorCode::InvalidReplicationFactor,
            KafkaErrorCode::InvalidReplicaAssignment,
            KafkaErrorCode::InvalidConfig,
            KafkaErrorCode::NotController,
            KafkaErrorCode::InvalidRequest,
            KafkaErrorCode::UnsupportedForMessageFormat,
            KafkaErrorCode::PolicyViolation,
            KafkaErrorCode::OutOfOrderSequenceNumber,
            KafkaErrorCode::DuplicateSequenceNumber,
            KafkaErrorCode::InvalidProducerEpoch,
            KafkaErrorCode::InvalidTxnState,
            KafkaErrorCode::InvalidProducerIdMapping,
            KafkaErrorCode::InvalidTransactionTimeout,
            KafkaErrorCode::ConcurrentTransactions,
            KafkaErrorCode::TransactionCoordinatorFenced,
            KafkaErrorCode::InvalidProducerId,
            KafkaErrorCode::InvalidSequenceNumber,
            KafkaErrorCode::InvalidEpoch,
            KafkaErrorCode::FencedLeaderEpoch,
            KafkaErrorCode::UnknownLeaderEpoch,
            KafkaErrorCode::UnsupportedCompressionType,
            KafkaErrorCode::StaleBrokerEpoch,
            KafkaErrorCode::OffsetNotAvailable,
            KafkaErrorCode::MemberIdRequired,
            KafkaErrorCode::PreferredLeaderNotAvailable,
            KafkaErrorCode::GroupMaxSizeReached,
            KafkaErrorCode::FencedInstanceId,
            KafkaErrorCode::EligibleLeadersNotAvailable,
            KafkaErrorCode::NoReassignmentInProgress,
            KafkaErrorCode::GroupSubscribedToTopic,
            KafkaErrorCode::InvalidRecord,
            KafkaErrorCode::UnstableOffsetCommit,
            KafkaErrorCode::ThrottlingQuotaExceeded,
            KafkaErrorCode::ProducerFenced,
            KafkaErrorCode::ResourceNotFound,
            KafkaErrorCode::DuplicateResource,
            KafkaErrorCode::UnacceptableCredential,
            KafkaErrorCode::InconsistentVoterSet,
            KafkaErrorCode::InvalidVotingKey,
            KafkaErrorCode::InvalidMetadataVersion,
            KafkaErrorCode::TopicDeletionDisabled,
            KafkaErrorCode::FencedLeaderEpoch2,
            KafkaErrorCode::KafkaStorageError,
            KafkaErrorCode::LogDirNotFound,
            KafkaErrorCode::SaslAuthenticationFailed,
            KafkaErrorCode::UnknownProducerId,
            KafkaErrorCode::ReassignmentInProgress,
            KafkaErrorCode::DelegationTokenAuthDisabled,
            KafkaErrorCode::DelegationTokenNotFound,
            KafkaErrorCode::DelegationTokenOwnerMismatch,
            KafkaErrorCode::DelegationTokenRequestNotAllowed,
            KafkaErrorCode::DelegationTokenAuthorizationFailed,
            KafkaErrorCode::DelegationTokenExpired,
            KafkaErrorCode::InvalidPrincipalType,
            KafkaErrorCode::NonEmptyGroup,
            KafkaErrorCode::GroupIdNotFound,
            KafkaErrorCode::FetchSessionIdNotFound,
            KafkaErrorCode::InvalidFetchSessionEpoch,
            KafkaErrorCode::ListenerNotFound,
            KafkaErrorCode::TopicExistsException,
            KafkaErrorCode::InvalidMetadata,
            KafkaErrorCode::InvalidUpdateVersion,
            KafkaErrorCode::FeatureUpdateFailed,
        ];

        for code in &all_codes {
            let v = code.as_i16();
            let recovered = KafkaErrorCode::from_i16(v)
                .unwrap_or_else(|| panic!("from_i16({v}) returned None for {code:?}"));
            assert_eq!(recovered.as_i16(), v, "roundtrip mismatch for {code:?}");
        }
    }

    #[test]
    fn test_unknown_code_returns_none() {
        assert_eq!(KafkaErrorCode::from_i16(9999), None);
        assert_eq!(KafkaErrorCode::from_i16(-9999), None);
    }

    #[test]
    fn test_critical_error_code_values() {
        // Verify values match Kafka standard
        assert_eq!(KafkaErrorCode::InvalidTxnState.as_i16(), 48);
        assert_eq!(KafkaErrorCode::InvalidProducerIdMapping.as_i16(), 49);
        assert_eq!(KafkaErrorCode::InvalidTransactionTimeout.as_i16(), 50);
        assert_eq!(KafkaErrorCode::ConcurrentTransactions.as_i16(), 51);
        assert_eq!(KafkaErrorCode::TransactionCoordinatorFenced.as_i16(), 52);
        assert_eq!(KafkaErrorCode::TopicAlreadyExists.as_i16(), 36);
    }
}
